### ISSUE TITLE
FeatureToggle not compatible with ASP.NET 5/vNext

### ISSUE THREAD

**Issue by DandyDev** [jason-roberts/FeatureToggle#109]
I'm porting an ASP.NET 4.6 app to the net ASP.NET 5 & MVC 6, and it uses the FeatureToggle library. It seems however, that even though I'm installing it through Nuget, anything under the `FeatureToggle.Core` namespace cannot be found.

Should FeatureToggle be compatible with ASP.NET 5? Is it able to handle the new way of configuration?

**Comment by jason-roberts** [comment]
Thanks @DandyDev - not tested as yet but it will be supported in a future version

**Comment by jason-roberts** [comment]
Once ASP.NET Core 1.0 is RTM or close to support will be added, it's a bit too far out at this stage to doing the development.

**Comment by aensidhe** [comment]
[They are close now, JFYI](https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/)

**Comment by SzymonSasin** [comment]
ASP.NET Core is now RC2 and has the go live promise. 

Will you accept the PR with netstandard code enabled?

**Comment by jason-roberts** [comment]
Hi @SzymonSasin - I'd still like to wait until v1 ships, I also am considering what v4 will look like - I'm assuming there will be no breaking changes by added support for core/asp?

**Comment by SzymonSasin** [comment]
I have tried and I am having some problems with referencing, that is a "missing System.Runtime" error.

In thery the .net core/standard dll should replace almost all of the "Code" projects. I think that Sql migth have to be taken outside similar to raven. otehr than that there should be no code changes.

**Comment by jason-roberts** [comment]
see #121
