### ISSUE TITLE
Remove installation of SampleFeatureToggle into the projects when installing via NuGet

### ISSUE THREAD

**Issue by samholder** [jason-roberts/FeatureToggle#117]
Whilst having a SampleFeatureToggle is a reasonable idea for people starting out, having this added to every project, every time you install/update the nuget package becomes annoying very quickly.

A model some other projects (essential diagnostics being one) follow is to have 2 nuget packages. One which just install the core libraries (FeatureToggle) and one which installs the samples and config examples (FeatureToggle.Config or FeatureToggle.Samples maybe). This allows the users the choice of whether they want to have the samples or not.

**Comment by jason-roberts** [comment]
Thanks @samholder - I agree - I will remove this for next release and consider the additional packages for future releases.

**Comment by jason-roberts** [comment]
Added #119 to capture idea for additional nugets

**Comment by JakeGinnivan** [comment]
This would be great, I am currently removing the sample feature toggle from about 20 projects because FeatureToggle is a transitive dependency so it got added everywhere :)

**Comment by jason-roberts** [comment]
Just doing this now. @JakeGinnivan do you think as far as semver is concerned you'd consider this a breaking change?

**Comment by JakeGinnivan** [comment]
Nope, it only happens during installation so it won't affect anyone existing.

**Comment by jason-roberts** [comment]
@JakeGinnivan yeah, that's kinda what I was thinking - thanks

**Comment by samholder** [comment]
Thanks! much appreciated!

**Comment by jason-roberts** [comment]
@samholder no worries
