### ISSUE TITLE
featuretoggle and core are not signed

### ISSUE THREAD

**Issue by msekkappan** [jason-roberts/FeatureToggle#124]
Our application requires the dlls to be signed, featuretoggle.dll and featuretoggle.core.dll that comes from Nuget are not signed.  I was able to download the source code, sign it with key and use it in our application.  But, we really want to get the dll referenced from Nuget.  Would you be able to put signed dlls on Nuget?

Thank you,
msekkappan

**Comment by jason-roberts** [comment]
Hi @msekkappan - please see https://github.com/jason-roberts/FeatureToggle/issues/75 - I may consider this again in the future but for now this is not on the roadmap
