### ISSUE TITLE
Web and Entity Framework Support

### ISSUE THREAD

**Issue by noahtk** [jason-roberts/FeatureToggle#125]
Is it possible to use the Feature Toggle library in a web project such as ASP.NET/SharePoint?  These two platforms do not have an App.config file so they must rely on a Web.config file only.  Also, is it possible to use the library with LINQ/Entity Framework vs using the SQL commands in the App.config file?  Please let me know if you need more information or if I'm not explaining anything well.

**Comment by jason-roberts** [comment]
Hi @noahtk - you can use FeatureToggle in a web app, you can configure the toggles in the web.config similar to how you would use an app.config in other application types. LINQ/EF is not supported.

web.config eg:

<configuration>
  <appSettings>
    <add key="FeatureToggle.PrintToggle" value="true" />
  </appSettings>
  <system.web>
    <compilation debug="true" targetFramework="4.5.2" />
    <httpRuntime targetFramework="4.5.2" />
  </system.web>
</configuration>
