### ISSUE TITLE
No strong name for v. 3.5

### ISSUE THREAD

**Issue by voroninp** [jason-roberts/FeatureToggle#126]
I've updated NuGet package to v.3.5.0 and got the following error:

> Error CS8002: Referenced assembly 'FeatureToggle, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

I do not understand why versions differ from NuGet package version.

**Comment by jason-roberts** [comment]
Hi @voroninp - from which version were you updating from?

**Comment by voroninp** [comment]
Pardon me, it was not signed earlier. My colleague did that... 
I updated from these versions, if you still need it =)

```xml
  <package id="FeatureToggle" version="3.2.0" targetFramework="net451" />
  <package id="FeatureToggle.Core" version="3.0.0" targetFramework="net451" />
```

**Comment by jason-roberts** [comment]
no worries @voroninp :)

**Comment by voroninp** [comment]
Ok =) Do you mind if I make a PR with assemblies signing enabled?

**Comment by jason-roberts** [comment]
hi @voroninp , this is not something that will currently be supported, please see https://github.com/jason-roberts/FeatureToggle/issues/75 and https://github.com/jason-roberts/FeatureToggle/issues/124
