### ISSUE TITLE
The connection string was not configured in <appSettings> 

### ISSUE THREAD

**Issue by eliassal** [jason-roberts/FeatureToggle#137]
Hi, I have an mvc  project  using this featureToggle and compiles with no issues in visual studio. 
I have 2 keys in the web.cong as follows:

> <add key="FeatureToggle.HomePageFeatureToggle.ConnectionStringName" value="MusicStoreEntities"/>
>     <add key="FeatureToggle.HomePageFeatureToggle.SqlStatement" value="select Enabled from FeatureToggles where Name = 'HomePagefeatureToggle'"/>
> 

The table FeatureToggles is populated with data. Running the site, I get the following error:

> The connection string was not configured in <appSettings> 
> with a key of 'FeatureToggle.HomePagefeatureToggle.ConnectionString' 
> or 
> 'FeatureToggle.HomePagefeatureToggle.ConnectionStringName' 
> nor in 
> <connectionStrings> with a name of 'FeatureToggle.HomePagefeatureToggle'.

which is not true.

Thanks for your help

**Comment by eliassal** [comment]
Here is my appSettings

> 
>   <appSettings>
>     <add key="ClientValidationEnabled" value="true"/>
>     <add key="UnobtrusiveJavaScriptEnabled" value="true"/>
>     <add key="FeatureToggle.HomePageFeatureToggle.ConnectionString" value="MusicStoreEntities"/>
>     <add key="FeatureToggle.HomePageFeatureToggle.SqlStatement" value="select Enabled from FeatureToggles where Name = 'HomePagefeatureToggle'"/>
>  </appSettings>

**Comment by eliassal** [comment]
Here is my appSettings

`` <appSettings>
    <add key="ClientValidationEnabled" value="true"/>
    <add key="UnobtrusiveJavaScriptEnabled" value="true"/>
    <add key="FeatureToggle.HomePageFeatureToggle.ConnectionString" value="MusicStoreEntities"/>
    <add key="FeatureToggle.HomePageFeatureToggle.SqlStatement" value="select Enabled from FeatureToggles where Name = 'HomePagefeatureToggle'"/>
   </appSettings>

**Comment by eliassal** [comment]
<appSettings>
    <add key="ClientValidationEnabled" value="true"/>
    <add key="UnobtrusiveJavaScriptEnabled" value="true"/>
    <add key="FeatureToggle.HomePageFeatureToggle.ConnectionString" value="MusicStoreEntities"/>
    <add key="FeatureToggle.HomePageFeatureToggle.SqlStatement" value="select Enabled from FeatureToggles where Name = 'HomePagefeatureToggle'"/>
 </appSettings>

**Comment by eliassal** [comment]
Here are the keys in appSettings 

> add key="FeatureToggle.HomePageFeatureToggle.ConnectionString" value="MusicStoreEntities"
> add key="FeatureToggle.HomePageFeatureToggle.SqlStatement" value="select Enabled from FeatureToggles where Name = 'HomePagefeatureToggle'"

**Comment by jason-roberts** [comment]
hi @eliassal the error says "HomePage**f**eatureToggle", your config has a different case F "HomePage**F**eatureToggle"

**Comment by eliassal** [comment]
Oh my bad, so it is case sensitive, thanks, yes it is working like a charm now
Salam
