### ISSUE TITLE
When installing FeatureToggle 4.0.2 to a "classic" .NET 4.6.1 app or library Nuget wants to install 47 other dependencies

### ISSUE THREAD

**Issue by bartread** [jason-roberts/FeatureToggle#160]
I wanted to use FeatureToggle 4.0.2 in our web application, which currently runs on "classic" .NET 4.6.1. However, when I tried to install via the NuGet package manager in Visual Studio 2017, it presented me with a list of 47 other dependencies - all different versions of system libraries relating to .NET Core and .NET Standard - that it wanted to install:

![image](https://user-images.githubusercontent.com/4139358/40668804-5f480ecc-635d-11e8-90f0-30067110b967.png)

This seems both excessive and unnecessary for a (relatively) simple utility library, as well as being liable to cause problems. Is it possible to build FeatureToggle 4.x.x and later, as per FeatureToggle 3.5.1, in such a way that these dependencies are not required, please?

(In the meantime I will use FeatureToggle 3.5.1 to avoid this issue.)

**Comment by jochenvangasse** [comment]
+1

**Comment by corkupine** [comment]
+1

**Comment by mikanyg** [comment]
This is not a FeatureToggle issue, but the way that .NET Standard packages work in .NET 4.6.1 which uses the packages.config style for dependency tracking. 

FeatureToggle package depends on FeatureToggle.Common which targets .NET Standard 1.6.1 which will add all the assembly references in "classic" projects. 

I think Microsoft tweaked this for packages targeting .NET Standard 2.0, but needs verification.

**Comment by jason-roberts** [comment]
Thanks for replying @mikanyg - version 5 is likely to be a fully/pure .NET standard library. https://github.com/jason-roberts/FeatureToggle/issues/155

**Comment by elovelan** [comment]
for the time-being, any consuming application can try using the [Microsoft.Packaging.Tools.Trimming](https://github.com/dotnet/standard/blob/master/Microsoft.Packaging.Tools.Trimming/docs/trimming.md) package
