### ISSUE TITLE
Using a Shared folder instead of SQLDatabase

### ISSUE THREAD

**Issue by moezyeddes** [jason-roberts/FeatureToggle#162]
I am starting looking for the Library FeatureToggle. I would Know if it is possible to use a Shared Folder with a JSON file to configure the Features instead of SQLServer  with a ConnectionString. what will be the modifications in the App.config or Web.Config in the appSettings. Thanks!!

**Comment by jason-roberts** [comment]
Hi @moezyeddes - that's not currently a supported scenario, you can however use the .config file to configure toggles but these would be local to each application rather than being shared across multiple applications. I've added #163 to capture this as a potential future improvement.
