### ISSUE TITLE
SqlFeatureToggle is disabled for .NET Core.

### ISSUE THREAD

**Issue by Wind010** [jason-roberts/FeatureToggle#164]
Is this due to non .NET Standard/Core dependencies?

**Comment by Wind010** [comment]
Seems like there is just more work to be done when it comes to the BooleanSqlServerProvider and loading the connection string and query details.

**Comment by mostafahedawa** [comment]
Hi @Wind010 Are you found solution for this issue ? or if there is any update ?

**Comment by Wind010** [comment]
I've committed changes to load up the AppSettings.*.json here:
https://github.com/Wind010/FeatureToggle/tree/develop

Expects the following configuration:
"FeatureToggle": {
   "SomeSqlServerToggle" : {
       "ConnectionString" : "Data Source=.\SQLEXPRESS;Initial Catalog=FeatureToggleIntegrationTests;Integrated Security=True;Pooling=False"" 
       "SqlStatement" : "SELECT select Value from Toggles where ToggleName = 'MySqlServerToggleFalse'"
   }
},

I haven't tested it nor written any unit-tests.  I made the changes on a machine that I didn't want to install the Win10 SDK which is required to build the solution.
