### ISSUE TITLE
IAP Windows Universal app business toggle

### ISSUE THREAD

**Issue by jason-roberts** [jason-roberts/FeatureToggle#59]

**Comment by jason-roberts** [comment]
Might push this out to v3.x perhaps just support for win 10, unsure at this point

**Comment by Odonno** [comment]
That should be great, any release date ?

**Comment by jason-roberts** [comment]
Sorry @Odonno not sure at this point, I want to wait for win10 / VS 2015 final so I can ensure that it's fully tested for different platforms and so I don't risk having to do re-work - stay tuned :)
