### ISSUE TITLE
NuGet package support for Core : portable-net45+win+wpa81+wp80

### ISSUE THREAD

**Issue by jason-roberts** [jason-roberts/FeatureToggle#70]

**Comment by Odonno** [comment]
Hi,

Just discovered your project. At first sight, it looks very great and easy to use in C#/XAML apps. I am disappointed that your package is reachable on Windows 8.1 but not on Windows Phone 8.1 (WinRT), in NuGet.

**Comment by jason-roberts** [comment]
Hi @Odonno - version 3 (currently in development) will add support for things like universal apps, phone etc eg: https://github.com/jason-roberts/FeatureToggle/issues/21
