### ISSUE TITLE
ApplyOnceFeatureToggle

### ISSUE THREAD

**Issue by Odonno** [jason-roberts/FeatureToggle#86]
As a developer, I want to create an ApplyOnce feature that will be used to show a feature only one time to the user.

Moreover, it could be designed in 2 ways :
1. ApplyOnceFeatureToggle (only once per app) by default
2. ApplyOnceUserFeatureToggle (only once per user, through multiple apps or app instances) using the Roaming settings

**Comment by jason-roberts** [comment]
Hi @Odonno - that's a really interesting idea, one potential problem with this is that if the app is re-installed then locally saved settings might be lost, etc. What kind of uses do you think this toggle will have?

**Comment by Odonno** [comment]
That's a good question. Clearly, I don't know about the local settings.

Here, I am talking about the Windows Phone / Windows 8 implementation. Indeed, you can use the LocalSettings container and I am not sure if it is removed when the app is removed... As a default one, we can use the RoamingSettings that is shared across all user devices.
