### ISSUE TITLE
Add Universal Windows Platform (Windows 10) support

### ISSUE THREAD

**Issue by jason-roberts** [jason-roberts/FeatureToggle#93]

**Comment by Odonno** [comment]
To target Windows 10, you only have to support both Windows 8.1 & Windows Phone 8.1. I suppose it is already done, isn't it ?

**Comment by jason-roberts** [comment]
Hi @Odonno - haven't looked into it in any details yet but hopefully it's that simple :) I still might add some tests specifically for it once everything is RTM - thanks :)

**Comment by Odonno** [comment]
I tested it today on Windows Universal (Windows 10) and it works fine. Indeed, it is the similar API of Windows 8.1.

**Comment by jason-roberts** [comment]
Awesome, thanks @Odonno for doing that :)

**Comment by jason-roberts** [comment]
Once Xbox One support is out of preview, will review this and see if any changes are needed before closing.
