### ISSUE TITLE
Allow BooleanSqlToggle to share a single <connnectionStrings> named connection

### ISSUE THREAD

**Issue by jason-roberts** [jason-roberts/FeatureToggle#96]
See #88 for more background

```
<connectionStrings>
    <add name="primary" connectionString="connection-string" />
</connectionStrings>

<appSettings>
    <add key="FeatureToggle.MyFeatureToggle.ConnectionStringName" value="primary" />
</appSettings>
```

**Comment by craig-wagner** [comment]
I think this can be done without requiring a different suffix and still maintain backward compatibility. Much like the DbContext constructor that takes a string (https://msdn.microsoft.com/en-us/library/gg679467(v=vs.113).aspx) which can be either a connection string or the name of a connection string, we can do the same thing here. It just seems simpler all around (configuring and coding).

**Comment by craig-wagner** [comment]
Just submitted a pull request (https://github.com/jason-roberts/FeatureToggle/pull/97) for this feature (with unit tests). This is the first time I've tried contributing. Followed the instructions on https://guides.github.com/activities/forking. Let me know if anything needs improvement.

**Comment by jason-roberts** [comment]
@craig-wagner - do you want to take a quick look at this https://github.com/jason-roberts/FeatureToggle/commit/d6a1564b80aea29a06bf1d854dc8f37837849370 just to check it's still operating as you expected? If all is well we can get v3.2 released this week :)

**Comment by craig-wagner** [comment]
@jason-roberts - Looks like it still works as I intended.
