### ISSUE TITLE
How to mock/test featuretoggles?

### ISSUE THREAD

**Issue by geirsagberg** [jason-roberts/FeatureToggle#99]
Given a piece of code that uses e.g. `SimpleFeatureToggle`, I see no way to mock the AppSettingsProvider for unit tests etc.

Any ideas how to solve this?

**Comment by jason-roberts** [comment]
Hi @geirsagberg , all toggles implement the interface IFeatureToggle, so using your mocking framework of choice just create a mock IFeatureToggle and set the mocks return value for the property "bool FeatureEnabled {get;}"
